config/routes.rb
HowTo::Application.routes.draw do

  resources :recipes do
    resources :steps
  end

  root to: 'recipes#index'


end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  attr_accessible :name, :steps

  has_many :steps, dependent: :destroy

end

app/models/step.rb
class Step < ActiveRecord::Base
  attr_accessible :instruction, :ordinality

  belongs_to :recipe

  validates :instruction, :presence => true
  validates :ordinality, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController

  before_filter :find_recipe
  before_filter :find_step, :only => [:show, :edit, :update, :destroy]

  def index
  end

  def show
    @step = Step.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @step }
    end
  end

  def new
    @step = @recipe.steps.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @step }
    end
  end

  def edit
    @step = Step.find(params[:id])
  end

  def create

    @step = @recipe.steps.build(params[:step])
    if @step.save
     # flash[:notice] = "Step has been created."
      redirect_to [@recipe]
    else
    #  flash[:alert] = "Step has not been created."
      render :action => "new"
    end

  end

  def update
    @step = Step.find(params[:id])

    respond_to do |format|
      if @step.update_attributes(params[:step])
        format.html { redirect_to @recipe, notice: 'Step was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @step.destroy
    redirect_to @recipe
    flash[:notice] = "Step was deleted."
  end

  private

    def find_recipe
      @recipe = Recipe.find(params[:recipe_id])
    end

    def find_step
      @step = @recipe.steps.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>How-To</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @recipes.each do |recipe| %>
    <tr>
      <td><%= recipe.name %></td>
      <td><%= link_to 'Show', recipe %></td>
      <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
      <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <br />
  <% end %>
</table>
<br />

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @recipe.name %><br />
</p>

<p>
  <table>
    <% @recipe.steps.each do |step| %>
    <tr>
      <td><%= step.ordinality %></td>
      <td><%= step.instruction %></td>
      <td><%= link_to 'Edit', edit_recipe_step_path(@recipe, step) %></td>
      <td><%= link_to 'Delete', [@recipe, step], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </table>
</p>

<%= link_to 'Add Step', new_recipe_step_path(@recipe) %> |
<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/steps/_form.html.erb
<%= form_for [@recipe, @step] do |f| %>
<p>
<%= f.label :ordinality %><br>
<%= f.text_field :ordinality %>
</p>
<p>
<%= f.label :instruction %><br>
<%= f.text_area :instruction %>
</p>
<%= f.submit %>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render 'form' %>

<%= link_to 'Back', recipe_path(@step.recipe) %>

app/views/steps/index.html.erb
<!-- <h1>Listing steps</h1>

<table>
  <tr>
    <th>instruction</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @steps.each do |step| %>
  <tr>
    <td><%= step.instruction %></td>
    <td><%= link_to 'Show', step %></td>
    <td><%= link_to 'Edit', edit_step_path(step) %></td>
    <td><%= link_to 'Destroy', step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Step', new_recipe_step_path %>
 -->

app/views/steps/new.html.erb
<h1>New step</h1>

<%= render 'form' %>

<%= link_to 'Back', recipe_path(@recipe) %>

app/views/steps/show.html.erb
<!--
<p id="notice"><%= notice %></p>

<p>
  <b>instruction:</b>
  <%= @step.instruction %>
</p>


<%= link_to 'Edit', edit_step_path(@step) %> |
<%= link_to 'Back', steps_path %>
 -->